---
title: "ORA and GSEA A-P axis analysis"
output: html_notebook
---


```{r}
library(clusterProfiler)
library(AnnotationHub)
library(ensembldb)
library(tidyverse)
library(org.Mm.eg.db)
# install.packages("svglite")
library(svglite)
# BiocManager::install("GSEABase")
library(GSEABase)
```


## Run ORA on the A-P dataset subset by response and presence of H3K27me3

```{r}
date <- '20210217'


runORAAPaxis <- function(background_genes, gene_set, label="") {
  
  clusterGoSummary <- enrichGO(gene = gene_set, 
                universe = background_genes,
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL",
                pAdjustMethod = "BH", 
                qvalueCutoff = 0.1, 
                readable = TRUE)
  
    if (!(dim(clusterGoSummary)[1] == 0)) { # exclude df's that have no observations
      size = 3
      plt <- dotplot(clusterGoSummary, showCategory=10, font.size = 6) + ggtitle(label) + 
        theme_classic(base_size = 6, base_family = "sans") + 
        theme(aspect.ratio = 2.0, axis.text.x=element_text(size=6), axis.text.y=element_text(size=6),
               axis.title=element_text(size=8,face="bold"))
      ggsave(file=paste0(fig_dir, "ora_", label, "-ORA.pdf"), plot=plt,  width=5, height=5 * 2.0)
      plt
      
      Emapplot <- emapplot(clusterGoSummary, pie_scale=0.5, line_scale=0.2, showCategory=15, layout = "nicely") + ggtitle(label) +
        theme(aspect.ratio = 1.0, axis.text.x=element_text(size=6), axis.text.y=element_text(size=6),
               axis.title=element_text(size=8,face="bold"))
      ggsave(file=paste(fig_dir, "ora_", label, "_EmaPlot.pdf", sep=''), plot=Emapplot,  width=size, height=size)
      Emapplot
      
      Heatplot <- heatplot(clusterGoSummary, showCategory=30) + ggtitle(label) +
        theme(axis.text.x=element_text(size=6), axis.text.y=element_text(size=6),
               axis.title=element_text(size=8,face="bold"))
      ggsave(file=paste(fig_dir, "ora_", label, "_Heatmap.pdf", sep=''), width=10, height=8, plot=Heatplot)
      Heatplot
    } else {
      print(paste0("You had no results for: ", label))
    }
}

```

## ORA on the clusters identified using the VAE
```{r}
data_dir <- '../../data/results/3_node_consistent_genes/functional/'
fig_dir <- '../../figures/3_node_consistent_genes/ora/'
clusterTraining <- read.csv(paste(data_dir, 'training-df_genes_3_node_consistent_genes_', date, '.csv', sep=''))

clusterTrainingGenes <- as.character(clusterTraining$entrezgene_id)

for (i in 0:5) {
  filename <-  paste(data_dir, 'cluster_', i,'_genes_3_node_consistent_genes_', date, '.csv', sep="")
  cluster_genes <- read.csv(filename)
  runORAAPaxis(clusterTrainingGenes, 
         as.character(cluster_genes$entrezgene_id),
         paste("ORA_cluster_1.25SD_", i + 1, sep=''))

}

tests <- c('PCA', 'UMAP', 'TSNE', 'PHATE', 'VAE-shallow', 'VAE-deep')
for (t in tests) {
  for (i in 0:2) {
    
    filename <-  paste(data_dir, t, '_', i, '-max_cons-3_', date, '.csv', sep="")
    print(filename)
    cluster_genes <- read.csv(filename)
    values <- as.character(cluster_genes$entrezgene_id)
    print(values[1])
    runORAAPaxis(clusterTrainingGenes, 
           values,
           paste("ORA_", t, '_max_', i + 1, sep=''))
    
    filename <-  paste(data_dir, t, '_', i, '-min_cons-3_', date, '.csv', sep="")
    cluster_genes <- read.csv(filename)
    values <- as.character(cluster_genes$entrezgene_id)
    print(values[1])
    runORAAPaxis(clusterTrainingGenes, 
           values,
           paste("ORA_", t, '_min_', i + 1, sep=''))

  }
}

```

## GSEA on the node ranks
```{r}
library(fgsea)
# Databases from here http://bioinf.wehi.edu.au/software/MSigDB/
rdata_dir <- '../../data/input/supps/'
load(paste0(rdata_dir, 'mouse_c7_v5p2_immuno.rdata'))
motifsMouse <- Mm.c7
load(paste0(rdata_dir,'mouse_c2_v5p2_curated_gene_sets.rdata'))
pathwaysMouse <- Mm.c2
load(paste0(rdata_dir,'mouse_c5_v5p2_go-gene-sets_28102020.rdata'))
goMouse <- Mm.c5
pathwaysMouse <- Mm.c2[sapply(names(Mm.c2), function(x){if (grepl("BIOCARTA|KEGG", x)) {1} else {0}}) > 0]

keggMouse <- readRDS('../../data/input/supps/Mm.c2.cp.kegg.v7.1.entrez.rds')

runUnadjGSEA <- function(ranked_values, outputPath, vaeLbl= "", numTop=4) {

  fgseaResvaeMotifs <- fgsea(motifsMouse, ranked_values, minSize=5, maxSize = 500)
  write_csv(fgseaResvaeMotifs[,c(-8)], paste(outputPath, vaeLbl, "_Motifs_", '.csv', sep=""))

  fgseaResKegg <- fgsea(keggMouse, ranked_values, minSize=5, maxSize = 500)
  write_csv(fgseaResKegg[,c(-8)], paste(outputPath, vaeLbl, "_KEGG_", '.csv', sep=""))

  fgseaResvaeGo <- fgsea(goMouse, ranked_values, minSize=5, maxSize = 500)
  write_csv(fgseaResvaeGo[,c(-8)], paste(outputPath, vaeLbl, "_GoSets", '.csv', sep=""))

  for (i in 1:numTop) {
      # Plot the top pathways and save these to a svg
      curGSEAFeature <- fgseaResvaeGo[order(-(NES)), ][i]$pathway
      plt <- plotEnrichment(goMouse[[curGSEAFeature]], ranked_values) + ggtitle(paste(curGSEAFeature, sep=" ")) 
      ggsave(file=paste(outputPath, vaeLbl, "_GoSets_NEG-nes_", curGSEAFeature, '.svg', sep=""), plot=plt, width=10, height=8)
      plt
            # Plot the top pathways and save these to a svg
      curGSEAFeature <- fgseaResvaeGo[order((NES)), ][i]$pathway
      plt <- plotEnrichment(goMouse[[curGSEAFeature]], ranked_values) + ggtitle(paste(curGSEAFeature, sep=" ")) 
      ggsave(file=paste(outputPath, vaeLbl, "_GoSets_POS-nes", curGSEAFeature, '.svg', sep=""), plot=plt, width=10, height=8)
      plt
  }
  
  fgseaResvaePath <- fgsea(pathwaysMouse, ranked_values, minSize=15, maxSize = 500)
  write_csv(fgseaResvaePath[,c(-8)], paste(outputPath, vaeLbl, "_Pathways_", '.csv', sep=""))
  
}

gsea_dir <- '../../figures/3_node_consistent_genes/gsea/'
for (i in 1:3) {
  df <- read.csv(paste(data_dir, 'vae-', i,'_3_node_consistent_genes_', date, '.csv', sep=""))
  ranked_values <- df$value
  names(ranked_values) <- as.character(df$entrezgene_id)
  runUnadjGSEA(
         ranked_values, 
         paste(gsea_dir, "/GSEA-unadj_", sep=''), 
         vaeLbl=paste("Cluster", i, sep=''), numTop=1)
}

```


## Test other methods as a rank

```{r}
gsea_dir <- '../../figures/3_node_consistent_genes/gsea/'

tests <- c('PCA', 'UMAP', 'TSNE', 'PHATE', 'VAE-LIN', 'VAE-deep')
for (t in tests) {
  for (i in 1:3) {
    df_t <- read.csv(paste(data_dir, t, '-', i,'_3_node_consistent_genes_', date, '.csv', sep=""))
    ranked_values <- df_t$value
    names(ranked_values) <- as.character(df_t$entrezgene_id)
    print(ranked_values[1,])
    runUnadjGSEA(
           ranked_values, 
           paste(gsea_dir, "/GSEA-unadj_", t, "_", sep=''), 
           vaeLbl=paste(t, i, sep=''), numTop=1)
  }
}



```
